### ISSUE TITLE
Not working with Facebook_212.0.0.28.110.apk (x86)

### ISSUE THREAD

**Issue by zorovhsvn** [tsarpaul/FBUnpinner#11]
Not working with Facebook_212.0.0.28.110.apk (x86)

[+] Patching TLS1.3 stack!
[+] Found TLS1.3 verifier at 0x2fb18e
[+] 22 bytes were overwritten!
[+] Found function at address 0x86829a
[+] 6 bytes were overwritten!

I am can't sniff packet and reject when start with Charlesproxy

**Comment by tsarpaul** [comment]
This is a proxy issue, check other issues about an explanation :)
