### ISSUE TITLE
Could not find the required code to patch!

### ISSUE THREAD

**Issue by lazyjohny500** [tsarpaul/FBUnpinner#12]
[+] Patching TLS1.3 stack!
[!] Could not find the required code to patch!

On Instagram apk:
com.instagram.android_72.0.0.21.98-132081655_minAPI19(x86)(nodpi)_apkmirror.com

**Comment by hongbowang** [comment]
@lazyjohny500 try the TLS1.2 patch in the paogram

**Comment by PreciousWarrior** [comment]
@lazyjohny500 how?
