### ISSUE TITLE
I patched but data encypt. Can you help me fix it

### ISSUE THREAD

**Issue by dev-ninjateam** [tsarpaul/FBUnpinner#14]
![image](https://user-images.githubusercontent.com/48278745/57195416-5689a580-6f7c-11e9-866f-f81071aea21d.png)

I patched but data encypt. Can you help me fix it

**Comment by hongbowang** [comment]
@dev-ninjateam  which version of facebook are you using

**Comment by hongbowang** [comment]
@dev-ninjateam it's don't worked for me , i can decrypt the data, but i can't get it

**Comment by dev-ninjateam** [comment]
It’s worked but not all. I can get about 40% requests and 60%  encrypt

**Comment by hongbowang** [comment]
i mean i can't get the patch worked, maybe it's a version issue. your data is encrypted because there is transport encryption in fb。i wan't know which version of facebook are you using, so i can solve the transport encryption.

**Comment by hongbowang** [comment]
@dev-ninjateam can you give me a copy of your facebook apk ?maybe i can solve the transport encryption

**Comment by dev-ninjateam** [comment]
I use 210 facebook apk x86 can u help me

**Comment by hongbowang** [comment]
i need your apk file in the path /data/app/com.facebook.katana-1.apk on your  x86 device. email : 595841527@qq.com

**Comment by dev-ninjateam** [comment]
Here can u help me
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-210-0-0-43-119-release/facebook-210-0-0-43-119-5-android-apk-download/

**Comment by silenthope1** [comment]
![image](https://user-images.githubusercontent.com/29290905/57249759-155dc800-7046-11e9-898e-dcf24eb30e0f.png)
check this

**Comment by dev-ninjateam** [comment]
OMG. Thank you verymuch. I did it
