### ISSUE TITLE
Can you please give me the patched file with the latest version of Facebook?

### ISSUE THREAD

**Issue by thanh-it** [tsarpaul/FBUnpinner#15]
I tried to follow the instructions but it did not work. Can you help me or send me the patched file? Thanks.

**Comment by dev-ninjateam** [comment]
Chào bạn :v

**Comment by thanh-it** [comment]
> Chào bạn :v

chào, không biết bạn có thể giúp mình cho bản facebook mới nhất hoặc gần đây đi qua Charles được không ?

**Comment by dev-ninjateam** [comment]
Chales k dùng đc cho facebook mới nhất đâu b mà api nó cũng k khác gì fb cũ đâu :v
