### ISSUE TITLE
After patch, burp still cannot intercept traffic

### ISSUE THREAD

**Issue by horsegitted** [tsarpaul/FBUnpinner#18]
![image](https://user-images.githubusercontent.com/16200132/64059075-7ad25780-cbe7-11e9-9207-0382e8b4f616.png)
Already using latest jdk 11.04, and latest burp community version, and installed burp ca cert in the Android 4.4 nexus phone, facebook version 233.0.0.36.117

**Comment by tsarpaul** [comment]
Seems like your burp/jdk doesn't support tls 1.3

**Comment by horsegitted** [comment]
indeed， already done， thanks
