### ISSUE TITLE
not working for lastest messanger 

### ISSUE THREAD

**Issue by onegithuber** [tsarpaul/FBUnpinner#19]
[+] Patching TLS1.3 stack!
[+] Found TLS1.3 verifier at 0x24d7f0
[+] 2 bytes were overwritten!
[+] Found function at address 0x32b7ab
[+] 4 bytes were overwritten!

when i replace the so the messanger is crash! i have chomd 777 for the so!

SoLoader: couldn't find DSO to load: libcoldstart.so caused by: /data/user/0/com.facebook.orca/lib-xzs/libcoldstart.so: open failed: EACCES (Permission denied)

**Comment by tsarpaul** [comment]
Doesn't seem like your chmod worked, you're geting EACCES which means the file wasn't even opened.
Can you redo the process and if this persists take a picture of `ls -l` of the directory where libcoldstart.so is.
