### ISSUE TITLE
Not working with Facebook-204.0.0.24.101.apk (x86)

### ISSUE THREAD

**Issue by aliveli186** [tsarpaul/FBUnpinner#2]
libcoldstart.so patches but doesn't remove the pinning. Tested in Android Emulator but didn't work.

Download the APK:
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-204-0-0-24-101-release/facebook-204-0-0-24-101-6-android-apk-download/

**Comment by tsarpaul** [comment]
Hi, the new versions are using TLS 1.3.
Many proxies do not support this protocol so I'm not sure whether they've changed the pinning mechanism or just using an unsupported protocol.
Either way I'll be trying to find/make my own TLS 1.3 supporting proxy and find out.

**Comment by itdecc** [comment]
which apk version is  working? thx

**Comment by zoneofsoft** [comment]
The latest version for android 4.4 + x86
https://yadi.sk/d/7Xcb8AXz3aAQc3
I hope you will succeed. Thank you for your hard work.

**Comment by tsarpaul** [comment]
> 
> 
> The latest version for android 4.4 + x86
> https://yadi.sk/d/7Xcb8AXz3aAQc3
> I hope you will succeed. Thank you for your hard work.

Hi, I'm working on an automatic solution for the newer versions.
I think anything before March 2018 should work with the current patcher.

**Comment by tsarpaul** [comment]
Added a patch for TLS1.3 for x86! 🎆

**Comment by zoneofsoft** [comment]
Thank you very much for your work. What version did you test? When I try the patch writes the following 
[+] Patching TLS1.3 stack!
[!] Could not find the required code to patch!

**Comment by tsarpaul** [comment]
I'll let you know when I get home,
only had the time to test it on 1 version

**Comment by zoneofsoft** [comment]
Excuse me. Another question is, which burpsuite do you use free or pro? 
The whole day looking for solution but not working TLS 1.3, tested on the website https://tls13.crypto.mozilla.org/
Getting Error Received fatal alert: protocol_version error/

**Comment by tsarpaul** [comment]
Free version with openjdk-11

**Comment by itdecc** [comment]
Thanks for work. Write please what version did you test?

**Comment by tsarpaul** [comment]
com.facebook.katana_210.0.0.43.119-143667991_minAPI26

I'll generalize the script for other versions soon.

**Comment by zoneofsoft** [comment]
You may be asked to share this version. And if you don't mind patched libcoldstart. 
What emulator do you use?

**Comment by tsarpaul** [comment]
Just run the script..
I use Genymotion - an x86 emulator for Android

**Comment by tsarpaul** [comment]
> 
> 
> Thank you very much for your work. What version did you test? When I try the patch writes the following
> [+] Patching TLS1.3 stack!
> [!] Could not find the required code to patch!

Which version did you use?
210 x86 and 211 x86 work well for me.

**Comment by tsarpaul** [comment]
Should be fixed, let me know if you find a version where it's not working

**Comment by clipvui2512** [comment]
How to root my emulator device ?

**Comment by zoneofsoft** [comment]
Thank you. On 211 everything works well. Have you tried to watch the traffic Facebook lite? It is very interesting to see the traffic from this version. But sniffer does not see it unfortunately. Can I get in touch with you via github?

**Comment by clipvui2512** [comment]
> Thank you. On 211 everything works well. Have you tried to watch the traffic Facebook lite? It is very interesting to see the traffic from this version. But sniffer does not see it unfortunately. Can I get in touch with you via github?

Hi
What is your android emulator software?

**Comment by zoneofsoft** [comment]
> > Thank you. On 211 everything works well. Have you tried to watch the traffic Facebook lite? It is very interesting to see the traffic from this version. But sniffer does not see it unfortunately. Can I get in touch with you via github?
> 
> Hi
> What is your android emulator software?

https://www.memuplay.com/home/Home/V2?l=ru

**Comment by silenthope1** [comment]
![image](https://user-images.githubusercontent.com/29290905/54076967-838e4480-42ba-11e9-8c4b-46d2a6469850.png)
did I do something wrong !!
I follow the steps over and over 
but still the same

**Comment by tsarpaul** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/29290905/54076967-838e4480-42ba-11e9-8c4b-46d2a6469850.png)
> did I do something wrong !!
> I follow the steps over and over
> but still the same

Yes, you're not using OpenJDK 11 - your Burp Suite version doesn't support TLS 1.3



> 
> 
> Thank you. On 211 everything works well. Have you tried to watch the traffic Facebook lite? It is very interesting to see the traffic from this version. But sniffer does not see it unfortunately. Can I get in touch with you via github?

You can reach me via Twitter for DMs


Closing this for now - issue solved :)

**Comment by clipvui2512** [comment]
Hi
How to setup BurpSuite with OpenJDK 11 ?

**Comment by silenthope1** [comment]
Yes just download burp suite jar file + open sdk 11
And go on
It worked for me

**Comment by theumairahmed** [comment]
The patcher frequently fails for Facebook Messenger (com.facebook.orca) versions, giving the error:

[+] Patching TLS1.3 stack!
[!] Could not find the required code to patch!

Tried the script with following releases of Facebook Messenger: March 2019, Feb 2019, March 2018, Jan 2018. Has anyone tried the patching script successfully on Facebook messenger app?

**Comment by tsarpaul** [comment]
Hi, which version and architecture exactly?

**Comment by theumairahmed** [comment]
I am running Google Nexus 5X - API26 on Genymotion Emulator which is x86 based. 
The specific versions of Facebook Messenger that I tested the patcher with are:

1- com.facebook.orca_147.0.0.25.86-84175400_minAPI21(x86)
2- com.facebook.orca_170.0.0.39.87-113613144_minAPI21(x86)
3- com.facebook.orca_171.0.0.28.108-114359499_minAPI21(x86)

**Comment by tsarpaul** [comment]
Those are old versions, try with orca_200+
There's currently a known issue that patching old versions doesn't work

**Comment by theumairahmed** [comment]
Now getting this error. I AM running burpsuite with OpenJDK 11 and able to record traffic from other apps. What exact steps should I follow after replacing the patched 'libcoldstart.so' file in /data/data/com.facebook.orca/lib-xzs?

![screenshot-2019-03-26_23 26 17 719](https://user-images.githubusercontent.com/17110823/55023431-96c14400-501e-11e9-831a-1fdb01e2c5dd.png)

**Comment by theumairahmed** [comment]
Same is happening with the Facebook app (Facebook 210.0.0.43.119 (x86)). I am sure that I am missing something during my unpinning procedure even after following every step in README.

**Comment by tsarpaul** [comment]
> 
> 
> Same is happening with the Facebook app (Facebook 210.0.0.43.119 (x86)). The apps just lose internet connectivity when I connect to internet via Burpsuite proxy. I am sure that I am missing something during my unpinning procedure even after following every step in README.

Many things can go wrong with your setup,
anyways lucky you - just a couple of days after I published this tool Facebook rolled out their own solution:
https://thehackernews.com/2019/03/facebook-whitehat-setting-hackers.html

**Comment by theumairahmed** [comment]
Oh that’s cool! Can you share your personal email or any other platform where I can contact you? Thanks for your contribution in this tool and keeping it updated!

**Comment by tsarpaul** [comment]
You can contact me via Twitter :)
