### ISSUE TITLE
Fb messenger message requests

### ISSUE THREAD

**Issue by silenthope1** [tsarpaul/FBUnpinner#3]
Any luck with capturing messages requests
I keep sending messages but still can't find any request

**Comment by tsarpaul** [comment]
Recent versions work for me, what's the issue exactly?

**Comment by silenthope1** [comment]
Can't find any request for messages that I sent
in Page manger and Messenger

**Comment by tsarpaul** [comment]
Not sure about Page Manager but Messenger works well.

**Comment by tsarpaul** [comment]
Closed since we have this issue now:
https://github.com/tsarpaul/FBUnpinner/issues/5
