### ISSUE TITLE
support for arm64 tls1.3

### ISSUE THREAD

**Issue by asad0x01** [tsarpaul/FBUnpinner#4]
Support for amr64 would be great.thanks in advance :)

**Comment by tsarpaul** [comment]
Can't test this on my own since I don't have an ARM64 device,
any emulators supporting it?
Added ARM32 so this should be next.

**Comment by asad0x01** [comment]
I’ve ARM64 device.let me know if you need any help :)
-- 
<https://about.me/asad0x01?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Asadul Islam
about.me/asad0x01
<https://about.me/asad0x01?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by tsarpaul** [comment]
Could you upload ARM64 libcoldstart.so for starters :)?

**Comment by asad0x01** [comment]
Here is the libcoldstart.so file for Facebook 212.0.0.28.110 Arm64
https://drive.google.com/file/d/1F3pdSmG7aA7rgF0II4IbhmRTWK7TU-5q/view?usp=drivesdk
.

**Comment by tsarpaul** [comment]
The script works as is lol (with the new patch 30 mins ago)

**Comment by tsarpaul** [comment]
The script works as is lol (with the new patch 30 mins ago)
