### ISSUE TITLE
TLS 1.3 stack

### ISSUE THREAD

**Issue by mAshraf9** [tsarpaul/FBUnpinner#8]
ERROR: Failed to patch ARM TLS 1.3 stack, something has gone wrong!

please help me thanks 👍

**Comment by tsarpaul** [comment]
I'll take a look when I get home, what version?

**Comment by mAshraf9** [comment]
facebook app version:149.0.0.40.71

**Comment by mAshraf9** [comment]
then I updated to 212 and still same error

**Comment by tsarpaul** [comment]
Fixed ARM32 and it works for me on 212 and 205.

**Comment by tsarpaul** [comment]
Seems like a heuristic I was using to detect TLS1.3 is unreliable - the TLS1.3 stack was added to the app's dependencies before it was actually used (I.E. ver 149) and the Certificate Verifier had a different implementation back then.

I'll probably separate the two patch modes (TLS1.2 and TLS1.3).

**Comment by viettools** [comment]
keep poting bro
thanks

**Comment by viettools** [comment]
Not related to Facebook
Is there any way to decode Viber?
@tsarpaul 
Thanks
