### ISSUE TITLE
Not working with Facebook Messenger (ver 207.0.0.13.99)

### ISSUE THREAD

**Issue by theumairahmed** [tsarpaul/FBUnpinner#9]
Emulator: Genymotion (Google Nexus 5X - API 26)
Proxy Software: Fiddler 

Followed the steps as mentioned in the README, replacing the libcoldstart.so file. However, when I apply the fiddler proxy to my emulator WiFi, Facebook Messenger stops getting internet access and nothing is loaded in the app. It works fine without applying the proxy though. 

Do I have to follow any other steps apart from what is mentioned in the REAMDE, like decompiling the application apk and adding a permission for user installed certificates in Android Manifest file? Also, which version of Facebook messenger have you tested for so far?

**Comment by tsarpaul** [comment]
Make sure your Fiddler supports TLS 1.3.
If it's based on Java use OpenJDK 11.

**Comment by theumairahmed** [comment]
Okay, Fiddler does not support TLS 1.3 as of now so Burpsuite is the only software we can use. But configuring Burpsuite with OpenJDK 11 is not very well documented. Kindly please add something related to their installation in README.

**Comment by tsarpaul** [comment]
Yeah seems like more than half of the issues being opened is proxy-related. I'll add something about it.
